### ISSUE TITLE
addSlide Bug in Chrome

### ISSUE THREAD

**Issue by scattond** [woocommerce/FlexSlider#1381]
Hi,

I'm building a webpage that uses flexslider and I'm trying to implement a function that allows the visitor to dynamically load a new slideshow. My code wipes out the current slides using the removeSlide() function and uses the addSlide() function to insert the new slides into the slideshow. It seems like it should be very straightforward and it is working in Safari and Firefox, but in Chrome, the slideshow appears to be a blank white box and the other slides are black boxes. An odd thing that is happening is when I then open my developer tools, the slides magically appear except for the cloned slides at the beginning and end of the slideshow - those still appear blank.

The content of my slides is html5 video, and I thought that might be the source of the problem so I tried testing with images, but the problem remained.

Here are the nuts and bolts of my function, which is very simple at the moment... I cut out some unnecessary parts to make it easier to read.

```
$.getJSON('/controllers/action.php, function( data ) {

    for (i=3; i >= 0; i--) {
        $('#flex').data('flexslider').removeSlide(i);
    }

    $.each (data, function (key, val) {
        $('#flex').data('flexslider').addSlide('<li><video><source src="/uploads/videos/creative/'+val.slug+'/'+val.video+'" type="video/mp4"></source></video></li>');
    });
});

```

Has anyone encountered this issue or does anyone have any thoughts about why this would only be broken in Chrome?

Thanks!

**Comment by scattond** [comment]
One more thing:

After continuing to tinker with it I've noticed the slides will also appear sometimes if I switch tabs momentarily.

**Comment by scattond** [comment]
Hi, just want to see if there are any thoughts on this?

**Comment by dfineberg** [comment]
I needed to do the exact same thing and was having similar issues. I fixed them by calling

`$("#flex").data("flexslider").flexslider(0);`

after I've switched up all the slides. My guess would be if you remove all the slides while an animation is going on then it scrolls off the side into blank space, so this just scrolls it back to the first slide after I'm done.

Hope this solves your problem!

**Comment by scattond** [comment]
I'm not sure that's the root of the problem for me unfortunately. I've done some more testing and have learned some additional information. I tried taking a lot of the variables out of the equation. I tried simply appending a new video to the page, outside of the flexbox, and I still get a blank video. I tried to just replace the entire html content of the page with a video and it still came up blank, BUT, when I try to do the same thing after removing the flex javascript file from my code, the video appears and plays normally.

I just tried a lot of different combinations of settings, and the video only works if flexslider is not included. Something about the way I'm including the flexslider.js is causing a conflict with chrome's ability to have an html5 video added to the dom after the page has loaded. I'm going to keep looking into it, but if anyone else has any thoughts or advice please let me know. Thanks!

**Comment by scattond** [comment]
Oh one more thing I've figured out is if I give the video a poster image, the poster will appear but the video will still not play or appear.

It seems what I said earlier about images not working was not correct, they appear to be showing up correctly now. I don't think I changed anything to make that happen, but maybe I did something inadvertently.

**Comment by scattond** [comment]
After some trial and error, I've found that removing line 935 of the code allows the videos to play:

``
slider.container.append(methods.uniqueID(slider.slides.first().clone().addClass('clone')).attr('aria-hidden', 'true')).prepend(methods.uniqueID(slider.slides.last().clone().addClass('clone')).attr('aria-hidden', 'true'));

``

When I replace this part of the code: methods.uniqueID(slider.slides.first()...

with a specific element: $('.class')....

The video works, so chrome doesn't seem to like that way of selecting the first and last slide in order to clone. I'm probably just going to make my own workaround for this in the meantime.

**Comment by XMMM1** [comment]
Hello,
sorry for jumping in into your topic. But i also have some problem (on new slide addition) on some similar task described in topic: https://github.com/woothemes/FlexSlider/issues/1408. Will you be so kind to check it and if you know any solutions to give me some advice?

Thanks in advance.
